language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_script:
- npm install -g --silent @angular/cli
script: 
- ng build --prod
deploy:
   provider: cloudfoundry
   username: jgsistem
   password: 
    secure: "JoKwBTbfyVW2bKdqjv8Z3Raqe8cLofCygZgM24PxLw2HQw/Uv60vwJ2fKlHcM7zzmuiaspyZJ02vtkfVTyEJcryq/BqiZ8ZIWZnFxMR6oKDLncR/ri91TmK34wNLOdirefYJB1KS7hY2fHVeFEa0EI2U+4cWohf5xCuFhYGhj5iungX72iwDCbaiV9JrvdJsUnRsEdHf8Yb3OKvTCYiIyBdO6sVMliOsJj3FyJKt36gBHg3q2/OcyM2avwtbYShbSCMK/jY7uz7/RmoPycrADkSeifPomjxsKiQsve1iNgvQkM2U720MZ1hx/ho640oBthdpK500yRi3/dOOtZL/8AefQXhSmA/d3YV0Gw8AUj0yVTV4UvZlESt460W49M1kafldyRO3APSE/yW9zTfU7IJ924/IjMCSaguGO8wtewOb67X07OPStabpBL1DfP/9LKTiRbSPuAa9vjVk2ATPAapA3pZ0vO8d/2Yhd63gZxbQvW9cks+U5FO570VXIhEwMzwYLG5iY/q3ymYoJrtUlz1kb5OcAfBn/chftZ9x3YU5+oydSSMrv+5FDfiPzXW5S3RKh2ZMnicDE0ohc2gDSGrQMi+RZO/g2Ossdinu8vTAveK+XQZIOTAQ84qLeN8A4XFjyXcUM+NcAcf7XNfIHqOu61EaZgLDjto0HBP3rHE="
   api: https://api.run.pivotal.io
   organization: JG17
   space: development