language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_script:
- npm install -g --silent @angular/cli
script: 
- ng build --prod
deploy:
   provider: cloudfoundry
   username: jgsistem
   password: .tr3vol17
   api: https://api.run.pivotal.io
   organization: JG15
   space: development